package com.github.butvinmitmo.highload.controller

import com.github.butvinmitmo.highload.dto.CreateInterpretationRequest
import com.github.butvinmitmo.highload.dto.CreateInterpretationResponse
import com.github.butvinmitmo.highload.dto.DeleteRequest
import com.github.butvinmitmo.highload.dto.InterpretationDto
import com.github.butvinmitmo.highload.dto.UpdateInterpretationRequest
import com.github.butvinmitmo.highload.service.InterpretationService
import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.Parameter
import io.swagger.v3.oas.annotations.responses.ApiResponse
import io.swagger.v3.oas.annotations.responses.ApiResponses
import io.swagger.v3.oas.annotations.tags.Tag
import jakarta.validation.Valid
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.DeleteMapping
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.PutMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.ResponseStatus
import org.springframework.web.bind.annotation.RestController
import java.util.UUID

@RestController
@RequestMapping("/api/v0.0.1/spreads/{spreadId}/interpretations")
@Tag(name = "Interpretations", description = "Manage interpretations for tarot spreads")
@Validated
class InterpretationController(
    private val interpretationService: InterpretationService,
) {
    @GetMapping
    @Operation(
        summary = "Get all interpretations for a spread",
        description =
            "Retrieves paginated interpretations for the specified spread, ordered by creation date (newest first)",
    )
    @ApiResponses(
        value = [
            ApiResponse(responseCode = "200", description = "Interpretations retrieved successfully"),
            ApiResponse(responseCode = "404", description = "Spread not found"),
        ],
    )
    fun getInterpretations(
        @Parameter(description = "Spread ID to get interpretations for", required = true)
        @PathVariable
        spreadId: UUID,
        @Parameter(description = "Page number (0-based)", example = "0")
        @RequestParam(defaultValue = "0")
        @Min(0)
        page: Int,
        @Parameter(description = "Page size (max 50)", example = "20")
        @RequestParam(defaultValue = "20")
        @Min(1)
        @Max(50)
        size: Int,
    ): ResponseEntity<List<InterpretationDto>> {
        val response = interpretationService.getInterpretations(spreadId, page, size)
        return ResponseEntity
            .ok()
            .header("X-Total-Count", response.totalElements.toString())
            .body(response.content)
    }

    @GetMapping("/{id}")
    @Operation(
        summary = "Get interpretation details",
        description = "Retrieves a specific interpretation by its ID",
    )
    @ApiResponses(
        value = [
            ApiResponse(responseCode = "200", description = "Interpretation found"),
            ApiResponse(responseCode = "404", description = "Interpretation or spread not found"),
        ],
    )
    fun getInterpretation(
        @Parameter(description = "Spread ID containing the interpretation", required = true)
        @PathVariable
        spreadId: UUID,
        @Parameter(description = "Interpretation ID", required = true)
        @PathVariable
        id: UUID,
    ): InterpretationDto = interpretationService.getInterpretation(spreadId, id)

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    @Operation(
        summary = "Add interpretation to a spread",
        description =
            "Creates a new interpretation. Each user can have only one interpretation per spread. " +
                "ID and timestamp are generated by PostgreSQL. Returns only the generated ID.",
    )
    @ApiResponses(
        value = [
            ApiResponse(responseCode = "201", description = "Interpretation added successfully, returns generated ID"),
            ApiResponse(responseCode = "404", description = "Spread or author not found"),
            ApiResponse(responseCode = "409", description = "User already has an interpretation for this spread"),
            ApiResponse(responseCode = "400", description = "Invalid request data"),
        ],
    )
    fun addInterpretation(
        @Parameter(description = "Spread ID to add interpretation to", required = true)
        @PathVariable
        spreadId: UUID,
        @Valid @RequestBody request: CreateInterpretationRequest,
    ): CreateInterpretationResponse = interpretationService.addInterpretation(spreadId, request)

    @PutMapping("/{id}")
    @Operation(
        summary = "Update interpretation",
        description = "Updates an existing interpretation. Only the interpretation author can update it.",
    )
    @ApiResponses(
        value = [
            ApiResponse(responseCode = "200", description = "Interpretation updated successfully"),
            ApiResponse(responseCode = "404", description = "Spread or interpretation not found"),
            ApiResponse(responseCode = "403", description = "User is not the author of the interpretation"),
            ApiResponse(responseCode = "400", description = "Invalid request data"),
        ],
    )
    fun updateInterpretation(
        @Parameter(description = "Spread ID containing the interpretation", required = true)
        @PathVariable
        spreadId: UUID,
        @Parameter(description = "Interpretation ID to update", required = true)
        @PathVariable
        id: UUID,
        @Valid @RequestBody request: UpdateInterpretationRequest,
    ): InterpretationDto = interpretationService.updateInterpretation(spreadId, id, request.authorId, request)

    @DeleteMapping("/{id}")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    @Operation(
        summary = "Delete interpretation",
        description = "Deletes an interpretation from a spread. Only the interpretation author can delete it.",
    )
    @ApiResponses(
        value = [
            ApiResponse(responseCode = "204", description = "Interpretation deleted successfully"),
            ApiResponse(responseCode = "404", description = "Spread or interpretation not found"),
            ApiResponse(responseCode = "403", description = "User is not the author of the interpretation"),
        ],
    )
    fun deleteInterpretation(
        @Parameter(description = "Spread ID containing the interpretation", required = true)
        @PathVariable
        spreadId: UUID,
        @Parameter(description = "Interpretation ID to delete", required = true)
        @PathVariable
        id: UUID,
        @RequestBody request: DeleteRequest,
    ) {
        interpretationService.deleteInterpretation(spreadId, id, request.userId)
    }
}
