package com.github.butvinmitmo.userservice.controller

import com.github.butvinmitmo.shared.dto.CreateUserRequest
import com.github.butvinmitmo.shared.dto.CreateUserResponse
import com.github.butvinmitmo.shared.dto.UpdateUserRequest
import com.github.butvinmitmo.shared.dto.UserDto
import com.github.butvinmitmo.userservice.service.UserService
import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.Parameter
import io.swagger.v3.oas.annotations.headers.Header
import io.swagger.v3.oas.annotations.media.ArraySchema
import io.swagger.v3.oas.annotations.media.Content
import io.swagger.v3.oas.annotations.media.Schema
import io.swagger.v3.oas.annotations.responses.ApiResponse
import io.swagger.v3.oas.annotations.responses.ApiResponses
import io.swagger.v3.oas.annotations.tags.Tag
import jakarta.validation.Valid
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.security.access.prepost.PreAuthorize
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.DeleteMapping
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.PutMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import java.util.UUID

@RestController
@RequestMapping("/api/v0.0.1/users")
@Tag(name = "Users", description = "User management operations")
@Validated
class UserController(
    private val userService: UserService,
) {
    @PostMapping
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(
        summary = "Create a new user",
        description =
            "Creates a new user with username and password. ADMIN only. " +
                "ID and timestamp are generated by PostgreSQL. Returns only the generated ID. " +
                "Returns 409 if username already exists.",
    )
    @ApiResponses(
        value = [
            ApiResponse(
                responseCode = "201",
                description = "User created successfully, returns generated ID",
                content = [Content(schema = Schema(implementation = CreateUserResponse::class))],
            ),
            ApiResponse(
                responseCode = "409",
                description = "User with this username already exists",
                content = [
                    Content(
                        schema = Schema(implementation = com.github.butvinmitmo.shared.dto.ErrorResponse::class),
                    ),
                ],
            ),
            ApiResponse(
                responseCode = "403",
                description = "User is not ADMIN",
                content = [
                    Content(
                        schema = Schema(implementation = com.github.butvinmitmo.shared.dto.ErrorResponse::class),
                    ),
                ],
            ),
            ApiResponse(
                responseCode = "400",
                description = "Invalid request data or weak password",
                content = [
                    Content(
                        schema =
                            Schema(
                                implementation = com.github.butvinmitmo.shared.dto.ValidationErrorResponse::class,
                            ),
                    ),
                ],
            ),
            ApiResponse(
                responseCode = "401",
                description = "Unauthorized",
                content = [
                    Content(
                        schema = Schema(implementation = com.github.butvinmitmo.shared.dto.ErrorResponse::class),
                    ),
                ],
            ),
        ],
    )
    fun createUser(
        @Valid @RequestBody request: CreateUserRequest,
    ): ResponseEntity<CreateUserResponse> {
        val response = userService.createUser(request)
        return ResponseEntity.status(HttpStatus.CREATED).body(response)
    }

    @GetMapping
    @Operation(
        summary = "Get paginated list of users",
        description = "Retrieves a paginated list of all users in the system. Requires authentication.",
    )
    @ApiResponses(
        value = [
            ApiResponse(
                responseCode = "200",
                description = "Users retrieved successfully",
                headers = [
                    Header(
                        name = "X-Total-Count",
                        description = "Total number of users",
                        schema = Schema(type = "integer"),
                    ),
                ],
                content = [Content(array = ArraySchema(schema = Schema(implementation = UserDto::class)))],
            ),
            ApiResponse(
                responseCode = "401",
                description = "Not authenticated",
                content = [
                    Content(
                        schema = Schema(implementation = com.github.butvinmitmo.shared.dto.ErrorResponse::class),
                    ),
                ],
            ),
        ],
    )
    fun getUsers(
        @Parameter(description = "Page number (0-based)", example = "0")
        @RequestParam(defaultValue = "0")
        @Min(0)
        page: Int,
        @Parameter(description = "Page size (max 50)", example = "20")
        @RequestParam(defaultValue = "20")
        @Min(1)
        @Max(50)
        size: Int,
    ): ResponseEntity<List<UserDto>> {
        val response = userService.getUsers(page, size)
        return ResponseEntity
            .ok()
            .header("X-Total-Count", response.totalElements.toString())
            .body(response.content)
    }

    @GetMapping("/{id}")
    @Operation(
        summary = "Get user by ID",
        description = "Retrieves a specific user by their UUID. Requires authentication.",
    )
    @ApiResponses(
        value = [
            ApiResponse(
                responseCode = "200",
                description = "User found",
                content = [Content(schema = Schema(implementation = UserDto::class))],
            ),
            ApiResponse(
                responseCode = "404",
                description = "User not found",
                content = [
                    Content(
                        schema = Schema(implementation = com.github.butvinmitmo.shared.dto.ErrorResponse::class),
                    ),
                ],
            ),
            ApiResponse(
                responseCode = "401",
                description = "Not authenticated",
                content = [
                    Content(
                        schema = Schema(implementation = com.github.butvinmitmo.shared.dto.ErrorResponse::class),
                    ),
                ],
            ),
        ],
    )
    fun getUser(
        @Parameter(description = "User ID", required = true)
        @PathVariable
        id: UUID,
    ): ResponseEntity<UserDto> {
        val user = userService.getUser(id)
        return ResponseEntity.ok(user)
    }

    @PutMapping("/{id}")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(
        summary = "Update user",
        description = "Updates an existing user's information. ADMIN only.",
    )
    @ApiResponses(
        value = [
            ApiResponse(
                responseCode = "200",
                description = "User updated successfully",
                content = [Content(schema = Schema(implementation = UserDto::class))],
            ),
            ApiResponse(
                responseCode = "404",
                description = "User not found",
                content = [
                    Content(
                        schema = Schema(implementation = com.github.butvinmitmo.shared.dto.ErrorResponse::class),
                    ),
                ],
            ),
            ApiResponse(
                responseCode = "403",
                description = "User is not ADMIN",
                content = [
                    Content(
                        schema = Schema(implementation = com.github.butvinmitmo.shared.dto.ErrorResponse::class),
                    ),
                ],
            ),
            ApiResponse(
                responseCode = "400",
                description = "Invalid request data",
                content = [
                    Content(
                        schema =
                            Schema(
                                implementation = com.github.butvinmitmo.shared.dto.ValidationErrorResponse::class,
                            ),
                    ),
                ],
            ),
            ApiResponse(
                responseCode = "401",
                description = "Unauthorized",
                content = [
                    Content(
                        schema = Schema(implementation = com.github.butvinmitmo.shared.dto.ErrorResponse::class),
                    ),
                ],
            ),
        ],
    )
    fun updateUser(
        @Parameter(description = "User ID", required = true)
        @PathVariable
        id: UUID,
        @Valid @RequestBody request: UpdateUserRequest,
    ): ResponseEntity<UserDto> {
        val updatedUser = userService.updateUser(id, request)
        return ResponseEntity.ok(updatedUser)
    }

    @DeleteMapping("/{id}")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(
        summary = "Delete user",
        description = "Deletes a user and all their associated data. ADMIN only.",
    )
    @ApiResponses(
        value = [
            ApiResponse(responseCode = "204", description = "User deleted successfully"),
            ApiResponse(
                responseCode = "404",
                description = "User not found",
                content = [
                    Content(
                        schema = Schema(implementation = com.github.butvinmitmo.shared.dto.ErrorResponse::class),
                    ),
                ],
            ),
            ApiResponse(
                responseCode = "403",
                description = "User is not ADMIN",
                content = [
                    Content(
                        schema = Schema(implementation = com.github.butvinmitmo.shared.dto.ErrorResponse::class),
                    ),
                ],
            ),
            ApiResponse(
                responseCode = "401",
                description = "Unauthorized",
                content = [
                    Content(
                        schema = Schema(implementation = com.github.butvinmitmo.shared.dto.ErrorResponse::class),
                    ),
                ],
            ),
        ],
    )
    fun deleteUser(
        @Parameter(description = "User ID", required = true)
        @PathVariable
        id: UUID,
    ): ResponseEntity<Void> {
        userService.deleteUser(id)
        return ResponseEntity.noContent().build()
    }
}
